# Generated by Django 4.0.1 on 2022-11-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='img',
            field=models.ImageField(default='', upload_to='contact/'),
        ),
    ]
